# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RAC_01' do

end

target 'RAC_01Tests' do

end

target 'RAC_01UITests' do

end

